version: "3.8"

services:
  app:
    profiles: ["app"]
    restart: always
    container_name: social-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PROJECT_PORT}
    environment:
      - VISUAL=nano
      - RAILS_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "${PROJECT_PORT}:${PROJECT_PORT}"
    networks:
      - social-api
    volumes:
      - ./logs:/rails/log
    depends_on:
      - postgres
      - kafka
      - zookeeper
    logging:
      driver: "local"

  postgres:
    container_name: postgres-${PROJECT_NAME}
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_ROL=${POSTGRES_ROL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - social-api
    restart: always

  pgadmin:
    container_name: pgadmin-${PROJECT_NAME}
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - social-api
    restart: always

  zookeeper:
    container_name: zookeeper-${PROJECT_NAME}
    image: "bitnami/zookeeper:3.8.0"
    restart: always
    ports:
      - ${ZOOKEEPER_PORT}:2181
    networks:
      - social-api
    volumes:
      - kafka:/data/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    logging:
      driver: "local"
      options:
        max-size: 10m
  kafka:
    container_name: kafka-${PROJECT_NAME}
    image: "bitnami/kafka:3.1.0"
    restart: always
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:${KAFKA_PORT}
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - social-api
    volumes:
      - kafka:/data/kafka
    logging:
      driver: "local"
      options:
        max-size: 10m

networks:
  social-api:
    driver: bridge

volumes:
  kafka:
  postgres:
  pgadmin:
